### PR TITLE
Added ability to provision publishing pages

### PR DESCRIPTION
**Pull request by SPParseError**
I created a new schema version named 2016-12, as it is the choice I made in my pull request on SharePoint/PnP-Sites-Core. I see there's an other pull request that just updated 2016-05 : I think we need some guidance on how to propose those ideas.

Changes required in PnP-Sites-Core has been added to PR #861 (SharePoint/PnP-Sites-Core)

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi Stéphane, we won't be merging this for now, since we are currently working slightly more extended schema changes, planned to get release in February release. We will absolutely take this into account as part of the needed changes, so that we get this capability merged. We rather now include all the known and listed gaps also from the Issues list of this repo, than just few specific ones. Thx for your input and let's keep this now open until the new schema has been designed and released.

**Comment by PaoloPia** [comment]
Hi Stéphane, I'm processing your submission but I'm having difficulties finding the differences between the original (201605) schema and your proposed new one (201612). Can you provide me more information or highlight the delta changes? Thanks.

**Comment by SPParseError** [comment]
Hi, the main difference is the ability to provision publishing pages. So there is a new <PublishingPage> list of elements in the existing <Publishing> element. Attached is a sample from our project
[sample.txt](https://github.com/SharePoint/PnP-Provisioning-Schema/files/926210/sample.txt)

**Comment by PaoloPia** [comment]
Hi Stéphane,
Right now this capability is out of schema version 201705. However, I'd ask you to re-submit these changes targeting the next schema version (most likely it will be 201801), which you can find in the experimental branch at the following URL: 

https://github.com/SharePoint/PnP-Provisioning-Schema/blob/experimental/OfficeDevPnP.ProvisioningSchema/ProvisioningSchema-2018-01.xsd

Please, keep in mind that having these changes at the schema level does not imply having support at the engine level. In fact, firstly we update the schema and then we update the engine accordingly.
In the meantime, I will close this item.

Thank you.

**Pull request closed without merging**
